"use client";

import { Download } from "lucide-react";
import { Button } from "../ui/button";

export default function DownloadSummaryButton({
  filename,
  title,
  summaryText,
  createdAt,
}: {
  filename: string;
  title: string;
  summaryText: string;
  createdAt: string;
}) {
  const handleDownload = () => {
    const summaryContent = `
#${title} 
Generated Summary 
Generated On: ${new Date(createdAt).toLocaleDateString()}
${summaryText}
OriginalFile: ${filename}
Generated By Quib
`;

    const blob = new Blob([summaryContent], { type: "text/plain" });

    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Summary-${title.replace(/[^a-z0-9]/gi, "_")}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };
  return (
    <Button
      size={"sm"}
      className="h-8 px-3 bg-neutral-100 text-neutral-500 hover:text-neutral-700 hover:bg-neutral-50"
      onClick={handleDownload}
    >
      <Download className="h-4 w-4 mr-1" />
      Download Summary
    </Button>
  );
}
